---
output: github_document
---

# Relatórios e apresentações automáticas

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Repositório principal do curso Relatórios e apresentações automáticas.

Inscreva-se no curso: https://loja.curso-r.com/relatorios-e-apresentacoes-automaticas.html

**Acesse o material completo do curso escolhendo uma das turmas abaixo**.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::kable(CursoRutils:::listar_turmas_recentes("relatorios")) 
```


<!-- **Trabalho de conclusão**: fazer o #tidytuesday da semana ou um à sua escolha. Fazer não só a visualização, mas uma apresentação ou relatório -->

## Pacotes necessários


```{r eval=FALSE, include=TRUE}
# Principal
principal <- c(
  "tidyverse",
  "xaringan",
  "flexdashboard",
  "xaringanthemer",
  "prettydoc",
  "patchwork",
  "fs",
  "janitor"
)
install.packages(principal)

# Pacotes instalados via GitHub
if (!require(remotes)) install.packages("remotes")
remotes::install_github("abjur/abjData")
remotes::install_github("cienciadedatos/dados")

# esses pacotes são para os showcases funcionarem
showcase <- c(
  "pagedown",
  "officedown",
  "rticles",
  "flextable",
  ## não instale o webshot ainda; vamos instalar em aula
  # "webshot",
  "officedown",  "bookdown"
)
install.packages(showcase)
```


```{r echo=FALSE}
materiais <- readr::read_lines("material.txt")
zip::zip("material_do_curso.zip", materiais)
```

